name: Checkov 
on:
  push
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.PC_SECRET}}
          use_enforcement_rules: true
